language: node_js

node_js:
  - '8'

cache:
  yarn: true
  directories:
  - node_modules

addons:
  firefox: latest
  chrome: stable

sudo: false

before_install:
  - export DISPLAY=:99.0;
  - sh -e /etc/init.d/xvfb start;
  - set -e;
  - npm install --global yarn

install:
  - yarn

jobs:
  include:
    - stage: Build / Test
      script: yarn prettier
    - stage: Build / Test
      script: yarn build
    - stage: Example
      script: yarn example:build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: example/public
        on:
          branch: master